#!/usr/bin/env python3
"""
PyInstaller Build Script for Python GUI Applications
Generates .spec file and builds application with optimal settings.

Usage:
    python build_pyinstaller.py [options]

Options:
    --name NAME         Application name (default: from main.py or directory)
    --main MAIN         Entry point file (default: main.py)
    --icon ICON         Icon file path (.ico for Windows, .icns for macOS)
    --console           Enable console window (disabled by default for GUI)
    --onefile           Create single executable
    --clean             Clean build artifacts before building
    --spec-only         Generate .spec file without building
"""

import subprocess
import sys
import os
import shutil
import argparse
from pathlib import Path
from textwrap import dedent


class PyInstallerBuildConfig:
    """Configuration manager for PyInstaller builds."""
    
    FRAMEWORK_HIDDEN_IMPORTS = {
        'pyside6': [
            'PySide6.QtCore',
            'PySide6.QtGui', 
            'PySide6.QtWidgets',
        ],
        'pyqt6': [
            'PyQt6.QtCore',
            'PyQt6.QtGui',
            'PyQt6.QtWidgets',
        ],
        'ctk': [
            'customtkinter',
            'darkdetect',
            'PIL',
        ],
        'flet': [
            'flet',
            'flet_core',
        ],
    }
    
    def __init__(self, args):
        self.main_file = Path(args.main)
        self.app_name = args.name or self._detect_app_name()
        self.icon = args.icon
        self.console = args.console
        self.onefile = args.onefile
        self.clean = args.clean
        self.spec_only = args.spec_only
        self.framework = self._detect_framework()
        self.output_dir = Path('dist')
        self.build_dir = Path('build')
        self.spec_file = Path(f'{self.app_name}.spec')
    
    def _detect_app_name(self) -> str:
        """Detect application name from main file or directory."""
        if self.main_file.stem != 'main':
            return self.main_file.stem
        return Path.cwd().name
    
    def _detect_framework(self) -> str:
        """Auto-detect GUI framework from imports."""
        try:
            content = self.main_file.read_text(encoding='utf-8')
            if 'PySide6' in content:
                return 'pyside6'
            elif 'PyQt6' in content:
                return 'pyqt6'
            elif 'customtkinter' in content:
                return 'ctk'
            elif 'flet' in content:
                return 'flet'
        except Exception:
            pass
        return 'pyside6'
    
    def get_hidden_imports(self) -> list:
        """Get hidden imports for the framework."""
        return self.FRAMEWORK_HIDDEN_IMPORTS.get(self.framework, [])
    
    def get_data_dirs(self) -> list:
        """Find data directories to include."""
        common_dirs = ['assets', 'resources', 'static', 'images', 'icons', 'fonts', 'themes']
        found = []
        for d in common_dirs:
            if Path(d).is_dir():
                found.append((d, d))
        return found


def generate_spec(config: PyInstallerBuildConfig) -> str:
    """Generate .spec file content."""
    
    # Format datas
    datas_str = repr(config.get_data_dirs())
    
    # Format hidden imports
    hidden_imports_str = repr(config.get_hidden_imports())
    
    # Icon handling
    if config.icon:
        icon_line = f"icon='{config.icon}',"
    else:
        icon_line = "icon=None,"
    
    # Console setting
    console_str = 'True' if config.console else 'False'
    
    spec_content = dedent(f'''
    # -*- mode: python ; coding: utf-8 -*-
    # Auto-generated by build_pyinstaller.py
    
    import sys
    from pathlib import Path
    
    block_cipher = None
    
    # Application metadata
    APP_NAME = '{config.app_name}'
    MAIN_SCRIPT = '{config.main_file}'
    
    a = Analysis(
        [MAIN_SCRIPT],
        pathex=[],
        binaries=[],
        datas={datas_str},
        hiddenimports={hidden_imports_str},
        hookspath=[],
        hooksconfig={{}},
        runtime_hooks=[],
        excludes=[
            'matplotlib',
            'numpy.testing',
            'scipy',
            'pandas',
        ],
        win_no_prefer_redirects=False,
        win_private_assemblies=False,
        cipher=block_cipher,
        noarchive=False,
    )
    
    pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
    ''').strip()
    
    if config.onefile:
        spec_content += dedent(f'''
    
    exe = EXE(
        pyz,
        a.scripts,
        a.binaries,
        a.zipfiles,
        a.datas,
        [],
        name=APP_NAME,
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        upx_exclude=[],
        runtime_tmpdir=None,
        console={console_str},
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        {icon_line}
    )
    ''')
    else:
        spec_content += dedent(f'''
    
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        name=APP_NAME,
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        console={console_str},
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        {icon_line}
    )
    
    coll = COLLECT(
        exe,
        a.binaries,
        a.zipfiles,
        a.datas,
        strip=False,
        upx=True,
        upx_exclude=[],
        name=APP_NAME,
    )
    ''')
    
    # macOS bundle
    if sys.platform == 'darwin':
        spec_content += dedent(f'''
    
    app = BUNDLE(
        coll,
        name='{config.app_name}.app',
        {icon_line.replace('icon=', 'icon=')}
        bundle_identifier='com.app.{config.app_name.lower()}',
    )
    ''')
    
    return spec_content


def run_build(config: PyInstallerBuildConfig):
    """Execute PyInstaller build with configuration."""
    
    # Validate main file exists
    if not config.main_file.exists():
        print(f"❌ Error: Main file '{config.main_file}' not found!")
        sys.exit(1)
    
    # Clean previous builds if requested
    if config.clean:
        print("🧹 Cleaning previous build artifacts...")
        for d in [config.output_dir, config.build_dir]:
            if d.exists():
                shutil.rmtree(d)
        if config.spec_file.exists():
            config.spec_file.unlink()
    
    # Generate .spec file
    print(f"📝 Generating {config.spec_file}...")
    spec_content = generate_spec(config)
    config.spec_file.write_text(spec_content, encoding='utf-8')
    
    if config.spec_only:
        print(f"✅ Spec file generated: {config.spec_file}")
        return
    
    # Build command
    cmd = [
        sys.executable, '-m', 'PyInstaller',
        '--clean',
        '--noconfirm',
        str(config.spec_file),
    ]
    
    # Print info
    print(f"🚀 Building '{config.app_name}' with PyInstaller...")
    print(f"📦 Framework: {config.framework}")
    print(f"📁 Output: {config.output_dir}")
    print(f"📄 Mode: {'onefile' if config.onefile else 'directory'}")
    print(f"\n💻 Command:\n{' '.join(cmd)}\n")
    
    # Execute
    try:
        result = subprocess.run(cmd, check=True)
        print(f"\n✅ Build successful! Output in '{config.output_dir}'")
    except subprocess.CalledProcessError as e:
        print(f"\n❌ Build failed with exit code {e.returncode}")
        sys.exit(e.returncode)
    except FileNotFoundError:
        print("\n❌ PyInstaller not found! Install with: pip install pyinstaller")
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description='Build Python GUI application with PyInstaller',
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument('--name', help='Application name')
    parser.add_argument('--main', default='main.py', help='Entry point file')
    parser.add_argument('--icon', help='Icon file path')
    parser.add_argument('--console', action='store_true', help='Enable console window')
    parser.add_argument('--onefile', action='store_true', help='Create single executable')
    parser.add_argument('--clean', action='store_true', help='Clean before building')
    parser.add_argument('--spec-only', action='store_true', help='Generate .spec only')
    
    args = parser.parse_args()
    config = PyInstallerBuildConfig(args)
    run_build(config)


if __name__ == '__main__':
    main()
